// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAe3486gx6QX9TPHzJfUEJ6hTj2rU1Eh80',
//     appId: '1:933388007622:web:0ee2febee9e7af415dffc7',
//     messagingSenderId: '933388007622',
//     projectId: 'ecommerceapp-b14a9',
//     authDomain: 'ecommerceapp-b14a9.firebaseapp.com',
//     storageBucket: 'ecommerceapp-b14a9.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDe9zqv_QOjQ65ZaR4QJuxB8wjhHFtHx30',
//     appId: '1:933388007622:android:52b208ec1be6c1395dffc7',
//     messagingSenderId: '933388007622',
//     projectId: 'ecommerceapp-b14a9',
//     storageBucket: 'ecommerceapp-b14a9.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDbNRK4tRMdypniBk5pxokh_G-9gULDRrs',
//     appId: '1:933388007622:ios:176e988017c503c65dffc7',
//     messagingSenderId: '933388007622',
//     projectId: 'ecommerceapp-b14a9',
//     storageBucket: 'ecommerceapp-b14a9.firebasestorage.app',
//     iosBundleId: 'com.syahrul.tstore',
//   );
// }
